"""LEVELS (fixed 2026-10-06 after TEST-001 v1 had inaudible SFX): level_db = target PEAK of the SFX relative to the VOICE PEAK
(after each SFX file is peak-normalised to 0 dBFS). Never apply it as raw file gain.
Sound Map source data. Each row: (trigger / scenario, sound design, free-library search query).
Category defaults set level (dB relative to voice) and timing (offset vs visual event). Build: python build_sound_map.py"""

# category: (title, default_level_dB, default_timing, rows)
CATS = {}

CATS["CAP"] = ("Caption & text events", -12, "on first frame of the text animation", [
 ("Small connector word appears (C1/C2 tiny italic)", "none, or ultra-soft tick only if nothing else plays in 0.5s", "ui tick soft"),
 ("Keyword appears big (C1 top tier / C2 headline)", "soft pop or tick, single", "ui pop soft"),
 ("Keyword SLAM (scale overshoot, heavy caps)", "short swish + low thump layered", "swish punch"),
 ("Typed headline, per character (C2 E14 style)", "soft typewriter/keyboard ticks, 1 per 2–3 chars, not every char", "typewriter soft key"),
 ("Typed sentence on dark HUD (E03)", "digital ticks + faint data chirps", "digital typing hud"),
 ("Karaoke: word lights up (C4)", "nothing per word; music carries it", "-"),
 ("Karaoke: highlighted brand-colour word", "tiny tick on that word only", "ui tick"),
 ("Heavy italic caps line appears (C3)", "punchy swish", "swish fast"),
 ("Number word in yellow (C3)", "bright tick + mini ding tail", "ui ding small"),
 ("Negative word in red (C3: 'WRONG', 'NEVER', 'MISTAKE')", "low dull thud or error buzz", "error buzz soft"),
 ("Question line ('WHY?')", "short rising whoosh into the word, stop on word", "whoosh rise short"),
 ("Two-tier lockup builds (small + big)", "tick on small, pop on big", "ui tick + pop"),
 ("Keyword behind head (C6) emerges from behind", "soft air swell", "air whoosh soft"),
 ("Word on body path / rotated (C7)", "quick swish following direction", "swish pass"),
 ("Silhouette flash then text (H7)", "camera flash pop + reverse hit", "camera flash pop"),
 ("Highlight bar wipes behind word", "marker swipe", "marker swipe"),
 ("Underline / oval drawn around word", "pen scribble short", "pen scribble"),
 ("Strike-through on wrong word", "pen scratch + error tick", "pen scratch"),
 ("Hand-drawn arrow points at object", "quick marker stroke", "marker stroke"),
 ("Sticker/label pops ('FREE', 'NEW')", "bubbly pop", "pop bubbly"),
 ("Emoji 3D pops", "cartoon boing small", "cartoon pop"),
 ("Quote marks appear", "paper tap", "paper tap"),
 ("Text glitch in (RGB split)", "digital glitch 0.15s", "glitch short"),
 ("Text pixel-assemble", "digital blip arpeggio", "digital blip"),
 ("Text blur-in with glow (E03)", "soft shimmer", "shimmer soft"),
 ("Big title fills screen (F2 card)", "deep whoosh + sub hit", "whoosh hit"),
 ("Vertical word scrolls through frame (E05 REFERENCES)", "long air pass", "air pass long"),
 ("List bullet 1/2/3 lands", "pops rising in pitch per item", "pop ascending"),
 ("Numbered badge pops (① ② ③)", "button click", "button click"),
 ("Previous bullet dims as next lands", "none", "-"),
 ("Text clears on shot change", "none (the transition sound covers it)", "-"),
 ("Subtitle line replaces itself (running subtitle)", "none", "-"),
 ("Keyword in money colour (৳ / $)", "coin tick", "coin single"),
 ("Keyword 'FREE'", "sparkle", "sparkle short"),
 ("Keyword 'SECRET'", "whisper swish / lock click", "lock click"),
 ("Keyword 'FAST / QUICK'", "zip", "zip fast"),
 ("Keyword 'SLOW'", "low stretched whoosh", "slow whoosh"),
 ("Keyword 'STOP'", "brake/record stop", "tape stop"),
 ("Keyword 'BOOM / EXPLODE'", "impact", "impact"),
 ("Keyword 'LOVE / HEART'", "soft heartbeat single", "heartbeat single"),
 ("Keyword 'TRUST / SAFE'", "soft chime", "chime soft"),
 ("Keyword 'WIN / SUCCESS / BEST'", "positive notification", "success chime"),
 ("Keyword 'FAIL / LOSE'", "descending tone", "fail tone"),
 ("Keyword 'GROW / INCREASE'", "rising pluck", "rise pluck"),
 ("Keyword 'DROP / DECREASE'", "falling tone", "fall tone"),
 ("Keyword 'WORLD / GLOBAL / INTERNATIONAL'", "airy pad swell", "air swell"),
 ("Keyword 'PREMIUM / LUXURY'", "glass ting", "glass ting"),
 ("Keyword 'INNOVATIVE / IDEA'", "light bulb click + ding", "light switch ding"),
 ("Keyword 'AI'", "digital chirp", "digital chirp"),
 ("Keyword 'DOCTOR' / name title", "soft page chime", "page chime"),
 ("Name lower-third (Dr. Shadly)", "soft swish + chime", "lower third swish"),
 ("CTA 'Comment X' / 'DM me'", "notification ping", "notification ping"),
 ("CTA 'Follow'", "button click + pop", "button click"),
 ("Timer/countdown text ticks (H8)", "clock tick each second", "clock tick"),
 ("Big number counts up", "tick train, speed follows count, end ding", "counter ticks"),
 ("Percent bar fills", "rising sweep", "rise sweep"),
 ("Price tag appears", "cash register small", "cash register"),
 ("Date / year appears (1915, 2025)", "typewriter clack", "typewriter single"),
 ("Bangla keyword slam", "same as English rules; never extra", "-"),
 ("Caption on top of busy music drop", "skip SFX, let drop speak", "-"),
])

CATS["TRN"] = ("Transitions", -9, "peak of the sound on the cut frame; whoosh starts 0.15–0.3s before", [
 ("Hard cut, same location", "none", "-"),
 ("Hard cut, new location (F3/E16)", "soft air whoosh into cut", "air whoosh"),
 ("Whip pan / tilt with blur (T2)", "fast whoosh matching direction", "whip whoosh"),
 ("Light-leak / gradient flash (T3)", "airy shimmer swell", "flash shimmer"),
 ("White flash", "camera flash / soft hit", "flash hit"),
 ("Colour state change to B&W (T4)", "low thump + filter-down", "low thump"),
 ("Red mono emphasis (T4)", "tension hit", "tension hit"),
 ("Back to colour from B&W", "reverse swell", "reverse swell"),
 ("Pixel dissolve on object (T5)", "digital blip arpeggio", "digital blip"),
 ("Spotlight iris open/close (T6)", "deep whoosh + low hum", "iris whoosh"),
 ("Keyhole / door wipe", "door creak short + whoosh", "door whoosh"),
 ("Ink blot spread wipe", "liquid swell", "ink splash"),
 ("Continuous camera through world (T7)", "one long soft wind, no per-object hits", "wind long"),
 ("Zoom through object into next scene", "rising whoosh, cut at peak", "zoom whoosh"),
 ("Card shrink to corner (PiP)", "swish small", "swish small"),
 ("Page turn / paper slide", "page flip", "page flip"),
 ("Slide-in from edge with shadow (E04)", "paper swish", "paper swish"),
 ("Glitch transition", "glitch burst", "glitch burst"),
 ("Defocus flash (T8)", "subtle air puff", "air puff"),
 ("Palette inversion dark↔light (E13)", "click + whoosh", "invert click"),
 ("Smear / letter stretch transition (E07)", "stretched whoosh", "stretch whoosh"),
 ("Match cut on motion", "none or continued motion sound", "-"),
 ("Cut to black 'breath' scene", "music drops out, room tone only", "-"),
 ("Black to reveal", "riser into impact", "riser impact"),
 ("Section change (step 1→2)", "whoosh + pop", "whoosh pop"),
 ("Chapter change (new location / outfit)", "music phrase change + air whoosh", "air whoosh"),
 ("Intro to talking head after cold open (F6)", "impact + sub", "impact sub"),
 ("Return from explainer to face (F5)", "reverse swell", "reverse swell"),
 ("Split-screen opens", "double swish", "swish double"),
 ("Split-screen closes", "single swish reverse", "swish reverse"),
 ("Grid of cards folds", "multiple soft clicks", "click multi"),
 ("Phone-UI overlay slides on", "phone swipe", "phone swipe"),
 ("Before/after slider wipe", "slider swish", "slider"),
 ("Rewind effect", "tape rewind", "tape rewind"),
 ("Freeze frame", "camera shutter + tape stop", "freeze shutter"),
 ("Speed ramp up", "rising whoosh", "speed up whoosh"),
 ("Speed ramp down / slow-mo", "deep slowed whoosh", "slow mo"),
 ("Shake / impact zoom", "impact", "impact"),
 ("Fade to end card", "music resolves, soft chime", "end chime"),
 ("Loop back to start (seamless reel)", "reverse whoosh into frame 1", "reverse whoosh"),
])

CATS["CAM"] = ("Camera moves & zooms", -14, "sound starts with the move, peak at the move's midpoint", [
 ("Punch-in 100→115% on sentence (T1)", "none (most of the time) / very soft air", "-"),
 ("Punch-in on punchline", "soft thump", "soft thump"),
 ("Focus zoom to detail (scalpel / screen)", "soft wind (Shadly preference)", "wind soft"),
 ("Slow push-in for emotion", "low pad swell", "pad swell"),
 ("Dolly back reveal", "air swell reverse", "air reveal"),
 ("Track down a website", "soft scroll + air", "scroll soft"),
 ("Lateral glide past cards", "single long wind, no per-card hits", "wind long"),
 ("Camera shake", "rumble short", "rumble"),
 ("Rack focus blur→sharp", "soft shimmer", "focus shimmer"),
 ("Orbit around 3D object", "slow circular whoosh", "orbit whoosh"),
 ("Drone top-down", "wind high", "wind high"),
 ("Tilt up to sky", "air rise", "air rise"),
 ("Crash zoom", "whoosh hit", "crash zoom"),
 ("Parallax drift (constant)", "none", "-"),
 ("Reframe to make room for text (E08)", "none", "-"),
 ("Zoom out to show grid of all work", "swell + soft chime", "swell chime"),
 ("Push into laptop screen", "air whoosh + faint fan hum", "laptop push"),
 ("Zoom into phone screen", "whoosh + phone tap", "phone zoom"),
 ("Handheld follow (walking)", "none (natural ambience)", "-"),
 ("Snap zoom on face (reaction)", "comedic zip", "zoom zip"),
])

CATS["UI"] = ("Web / app / screen", -14, "on the visual action frame", [
 ("Mouse cursor moves", "none", "-"), ("Mouse click", "mouse click", "mouse click"), ("Double click", "double click", "double click"),
 ("Button press on site", "UI button click", "ui button"), ("Hover glow on button", "tiny tick", "ui hover"),
 ("Page scroll", "soft scroll wheel", "scroll wheel"), ("Fast scroll", "scroll whoosh", "scroll fast"),
 ("Page load", "subtle digital whoosh", "page load"), ("Loading spinner", "soft loop blips", "loading blip"),
 ("Form field typing", "keyboard typing light", "keyboard typing"), ("Form submit success", "success chime", "success"),
 ("Error message", "error buzz", "error"), ("Notification banner", "notification", "notification"),
 ("Phone tap", "phone tap", "phone tap"), ("Phone swipe", "swipe", "phone swipe"), ("Phone unlock", "unlock click", "unlock"),
 ("Message sent (WhatsApp)", "message whoosh", "message sent"), ("Message received", "message pop", "message received"),
 ("Like / heart tap", "pop + sparkle", "like pop"), ("Comment appears", "bubble pop", "comment pop"),
 ("Follower count rises", "tick train + ding", "counter ticks"), ("Appointment booked", "calendar ding", "booking chime"),
 ("Google search typed", "typing + search click", "search typing"), ("Search results appear", "soft whoosh", "results whoosh"),
 ("Google Maps pin drop", "pin drop", "pin drop"), ("Star rating fills 1–5", "5 ascending ticks", "star rating"),
 ("Review card appears", "card pop", "card pop"), ("Website hero reveal", "soft swell + click", "hero reveal"),
 ("Mobile view toggle", "switch click", "switch"), ("Dark mode toggle", "switch click + whoosh", "toggle"),
 ("Code being written", "fast keyboard", "keyboard fast"), ("Code compiles / build success", "success blip", "build success"),
 ("Website goes live", "launch whoosh + chime", "launch"), ("Domain / URL typed", "typing", "typing"),
 ("Admin panel edit saved", "save click", "save"), ("Drag & drop", "drag swish + drop tap", "drag drop"),
 ("Popup modal opens", "pop", "modal pop"), ("Popup closes", "reverse pop", "modal close"),
 ("Video play button", "play click", "play click"), ("Screenshot taken", "camera shutter", "screenshot"),
 ("Chat AI answer streams", "soft digital typing", "ai typing"), ("AI generates image", "magic shimmer", "magic"),
 ("Analytics chart rises", "rising pluck", "chart rise"), ("Analytics chart falls", "falling tone", "chart fall"),
 ("Laptop open", "laptop open", "laptop open"), ("Laptop close", "laptop close", "laptop close"),
 ("Phone vibrate", "vibration", "phone vibrate"), ("Email sent", "email whoosh", "email sent"),
 ("Instagram story swipe", "swipe", "swipe"), ("Facebook ad shown", "notification soft", "notification"),
 ("QR code scan", "scanner beep", "scan beep"), ("Payment success (bKash/card)", "payment success", "payment success"),
 ("Website speed test score", "counter ticks + ding", "score"), ("SEO rank climbs", "rising arpeggio", "rank up"),
 ("Broken old website shown", "glitch + error", "broken glitch"), ("Website before → after", "slider swish + chime", "before after"),
 ("Multiple websites grid", "soft click per card (max 4)", "grid click"), ("Browser tab opens", "tab pop", "tab pop"),
])

CATS["MONEY"] = ("Money, business, numbers", -11, "on the visual frame", [
 ("Taka notes appear", "paper money rustle", "money rustle"), ("Coins fall", "coins drop", "coins drop"),
 ("Single coin", "coin ting", "coin"), ("Money rain", "money shower", "money rain"), ("Cash register / sale", "cash register", "cash register"),
 ("Wallet opens", "zipper / leather", "wallet"), ("Money lost / wasted", "coin falling down drain + low tone", "money lose"),
 ("Money saved", "piggy bank coin + ding", "piggy bank"), ("Price drop", "falling tone + tick", "price drop"),
 ("Profit rises", "rising arpeggio", "profit"), ("Invoice / bill", "paper + stamp", "stamp"), ("Contract signed", "pen sign", "pen sign"),
 ("Handshake deal", "soft clap/hand", "handshake"), ("Calculator", "calculator keys", "calculator"), ("Bank transfer", "digital whoosh + ding", "transfer"),
 ("Credit card swipe", "card swipe", "card swipe"), ("Gold / premium", "glass ting", "ting"), ("Discount %", "pop + sparkle", "discount"),
 ("Expensive!", "cash register + gasp-free sting", "sting"), ("Free!", "sparkle", "sparkle"), ("Budget chart", "pencil + tick", "chart"),
 ("Stock market down", "falling synth", "market down"), ("Stock up", "rising synth", "market up"), ("ROI / results reveal", "drum hit + chime", "reveal hit"),
 ("Clients count up", "tick train", "counter"), ("Package tiers ($550/$800)", "card pop each", "card pop"), ("Add-on +$200", "plus pop", "plus pop"),
 ("Money flying away", "wind + paper", "paper wind"), ("Bag of money drops", "heavy thud", "money bag"), ("Hourly rate / time is money", "clock tick + coin", "clock coin"),
])

CATS["TIME"] = ("Time", -12, "on the visual frame", [
 ("Clock appears", "clock tick", "clock tick"), ("Clock spins fast", "fast ticking", "fast clock"), ("Alarm 2AM", "alarm short", "alarm"),
 ("Calendar pages flip", "page flips fast", "calendar flip"), ("Hourglass", "sand trickle", "sand"), ("Deadline", "tension tick + hit", "deadline"),
 ("Years pass", "time whoosh reverse", "time pass"), ("Stopwatch start", "stopwatch click", "stopwatch"), ("Countdown 3-2-1", "beeps", "countdown beep"),
 ("Late / missed", "descending tone", "missed"), ("Instant / seconds", "zip", "zip"), ("Waiting room", "soft clock + room tone", "waiting room"),
 ("Morning", "birds light", "birds"), ("Night", "crickets light", "crickets"), ("Weekend", "light chime", "chime"),
])

CATS["MED"] = ("Medical & clinic (doctor audience)", -12, "on the visual frame; keep realistic and gentle, never gory", [
 ("Scalpel shown", "metal glint (dagger shing, soft)", "metal shing"), ("Incision line drawn", "fine slice", "slice soft"),
 ("Surgical instruments tray", "metal clink", "metal clink"), ("Suture / stitch lands", "soft tick per stitch", "stitch tick"),
 ("Heartbeat / ECG", "heartbeat + monitor beep", "ecg beep"), ("Flatline (danger)", "monitor flat tone (short, careful)", "flatline"),
 ("Stethoscope", "soft heartbeat muffled", "stethoscope"), ("Syringe", "syringe squirt soft", "syringe"), ("Pills", "pill bottle rattle", "pills"),
 ("X-ray / scan", "scanner hum", "scanner"), ("MRI", "low mechanical hum", "mri"), ("Lab test tube", "glass clink", "test tube"),
 ("Dental drill", "short drill whir (very brief)", "dental drill"), ("Tooth sparkle (clean)", "sparkle ting", "tooth sparkle"),
 ("Dental chair recline", "hydraulic", "chair hydraulic"), ("Braces / aligner click", "plastic click", "plastic click"),
 ("Eye / retina", "soft whoosh + focus", "eye focus"), ("Brain", "neural shimmer", "neural"), ("Bone / ortho", "soft knock", "bone knock"),
 ("Ambulance", "siren distant short", "siren"), ("Hospital corridor", "room tone + footsteps", "hospital ambience"),
 ("Doctor's chamber door", "door open", "door"), ("Patient waiting room", "murmur soft", "murmur"), ("Prescription written", "pen writing", "pen write"),
 ("Medical report printed", "printer", "printer"), ("Hand wash / sanitizer", "water/squirt", "sanitizer"), ("Gloves snap", "glove snap", "glove snap"),
 ("Mask on", "fabric rustle", "fabric"), ("Diagnosis reveal", "soft chime", "chime"), ("Recovery / healthy", "warm swell", "warm swell"),
 ("Pain / problem", "low tension tone", "tension"), ("Medical certificate / degree", "paper + stamp", "stamp"),
 ("Award / trophy", "trophy ting + applause short", "trophy"), ("Appointment phone call", "phone ring short", "phone ring"),
 ("Telemedicine call connects", "video call connect", "call connect"), ("Health app notification", "notification", "notification"),
 ("Microscope", "focus click", "microscope"), ("Laparoscopy screen", "monitor beep soft", "monitor"), ("Operation theatre lights on", "light switch heavy + hum", "ot light"),
 ("Blood pressure cuff", "pump squeeze", "bp pump"), ("Thermometer beep", "beep", "thermometer"), ("Wheelchair", "wheel roll", "wheel"),
 ("Baby / pediatric", "soft rattle", "rattle"), ("Skin / derma", "soft shimmer", "shimmer"), ("Heart (cardiology icon)", "single heartbeat", "heartbeat"),
])

CATS["TECH"] = ("Tech, AI, digital", -12, "on the visual frame", [
 ("AI robot appears", "robot chirp", "robot chirp"), ("Neural network lines", "data shimmer", "data"), ("Chip / processor", "electric zap soft", "zap"),
 ("Server / cloud", "server hum + whoosh", "server"), ("Data flowing", "digital stream", "data stream"), ("Hologram UI", "hologram shimmer", "hologram"),
 ("Scan line", "scanner sweep", "scan"), ("Lock / security", "lock click", "lock"), ("Unlock", "unlock", "unlock"), ("Hack / glitch", "glitch", "glitch"),
 ("WiFi / signal", "signal blips", "signal"), ("Battery charge", "charge rise", "charge"), ("Power on", "power up", "power up"), ("Power off", "power down", "power down"),
 ("Camera recording (REC)", "beep start", "rec beep"), ("Microphone", "mic tap", "mic tap"), ("Headphones", "soft click", "click"),
 ("3D printer", "mechanical whir", "printer 3d"), ("Satellite / globe digital", "space swell", "space"), ("Rocket launch (growth)", "rocket whoosh", "rocket"),
 ("Light bulb idea", "bulb click + ding", "bulb"), ("Gear / process", "mechanical gear", "gear"), ("Magnet", "magnet hum", "magnet"),
 ("Laser", "laser zap", "laser"), ("Pixel art", "8-bit blip", "8bit"), ("Game / level up", "level up", "level up"),
 ("Download", "download whoosh", "download"), ("Upload", "upload rise", "upload"), ("Sync", "sync chime", "sync"), ("Delete", "trash crumple", "trash"),
])

CATS["OBJ"] = ("Everyday objects & meaning", -12, "on the visual frame", [
 ("Book opens", "book open", "book"), ("Pages flip", "page flip", "page"), ("Pen writes", "pen write", "pen"), ("Pencil sketch", "pencil", "pencil"),
 ("Paper crumple (bad idea)", "crumple", "crumple"), ("Paper tear", "tear", "paper tear"), ("Sticky note", "paper slap", "sticky"), ("Stamp approved", "stamp", "stamp"),
 ("Envelope / letter", "paper slide", "envelope"), ("Box / package", "cardboard", "box"), ("Gift opened", "ribbon + sparkle", "gift"),
 ("Key / unlock success", "key jingle", "keys"), ("Door opens (opportunity)", "door open", "door"), ("Door closes", "door close", "door close"),
 ("Light switch", "switch", "switch"), ("Candle", "match strike", "match"), ("Fire (passion)", "fire whoosh", "fire"), ("Water drop", "drop", "drop"),
 ("Glass breaks (shock)", "glass break short", "glass break"), ("Balloon pop", "pop", "balloon"), ("Bell", "bell", "bell"), ("Whistle", "whistle", "whistle"),
 ("Magnifying glass (search)", "zoom shimmer", "magnify"), ("Puzzle piece fits", "click fit", "puzzle"), ("Lego / building blocks", "plastic clicks", "lego"),
 ("Hammer / building", "hammer", "hammer"), ("Brick wall (obstacle)", "thud", "thud"), ("Ladder climb", "steps", "climb"), ("Stairs / growth steps", "ascending taps", "steps up"),
 ("Trophy", "ting", "trophy"), ("Medal", "medal clink", "medal"), ("Crown", "regal shimmer", "crown"), ("Diamond", "diamond sparkle", "diamond"),
 ("Globe spins", "air whoosh", "globe"), ("Map pin", "pin drop", "pin"), ("Compass", "click", "compass"), ("Rocket", "rocket", "rocket"),
 ("Car (speed)", "car pass", "car pass"), ("Motorbike", "engine rev short", "engine"), ("Running person", "footsteps fast", "running"),
 ("Shoes lace up", "lace", "lace"), ("Plane", "plane pass", "plane"), ("Train", "train pass", "train"), ("Fishing hook drops", "hook plop", "plop"),
 ("Arrow hits target", "arrow thunk", "arrow"), ("Dart", "dart", "dart"), ("Chess move (strategy)", "chess piece tap", "chess"), ("Dice", "dice roll", "dice"),
 ("Camera photo", "shutter", "shutter"), ("Polaroid print", "polaroid eject", "polaroid"), ("Film reel", "projector", "projector"),
 ("Mirror (self)", "shimmer", "shimmer"), ("Umbrella (protection)", "umbrella open", "umbrella"), ("Shield", "metal block", "shield"),
 ("Parachute", "fabric whoosh", "parachute"), ("Crutches (weakness)", "wood knock", "wood"), ("Bubble", "bubble", "bubble"), ("Spring / bounce", "boing", "boing"),
 ("Brain thinking", "soft neural", "neural"), ("Eye blink", "blink tick", "blink"), ("Ear / listen", "air muffle", "muffle"), ("Megaphone (announce)", "megaphone", "megaphone"),
 ("Loudspeaker", "mic feedback very short", "feedback"), ("Microphone podcast", "mic tap", "mic"), ("Coffee cup", "cup clink + pour", "coffee"), ("Tea Bangla cha", "pour + clink", "tea"),
])

CATS["NAT"] = ("Nature, ambience, emotion", -16, "bed under the scene, fade in 0.3s", [
 ("Sunrise / new start", "birds + warm pad", "morning birds"), ("Rain (sad/calm)", "rain soft", "rain"), ("Thunder (problem)", "thunder distant", "thunder"),
 ("Wind (change)", "wind", "wind"), ("Ocean / calm", "waves", "waves"), ("Forest", "forest ambience", "forest"), ("City busy", "city ambience", "city"),
 ("Dhaka traffic", "traffic horns soft", "traffic"), ("Crowd / audience", "crowd murmur", "crowd"), ("Applause (achievement)", "applause short", "applause"),
 ("Laugh (light humour)", "light laugh", "laugh"), ("Gasp-worthy moment", "orchestral sting short", "sting"), ("Suspense", "low drone", "drone"),
 ("Calm / trust", "soft pad", "pad"), ("Victory", "rising brass short", "victory"), ("Mistake / oops", "comedic boing", "oops"), ("Shock", "impact + reverse", "shock"),
 ("Sad", "low piano note", "piano low"), ("Happy", "pluck melody short", "happy pluck"), ("Curiosity", "music box tick", "curious"),
])

CATS["PEOPLE"] = ("People & actions", -14, "on the action frame", [
 ("Footsteps walking in", "footsteps", "footsteps"), ("Sit down", "chair", "chair"), ("Clap", "single clap", "clap"), ("Snap fingers (instant)", "snap", "snap"),
 ("Thumbs up", "pop", "pop"), ("Point at screen", "tick", "tick"), ("Hand wave", "air swish", "swish"), ("High five", "slap", "high five"),
 ("Phone pick up", "pick up", "phone pick"), ("Typing on laptop", "keyboard", "keyboard"), ("Writing notes", "pen", "pen"), ("Heartbeat nervous", "heartbeat", "heartbeat"),
 ("Breath / relief", "exhale (non-vocal synth)", "breath"), ("Doorbell / visitor", "doorbell", "doorbell"), ("Patient smiling", "warm chime", "chime"),
 ("Team working", "office ambience", "office"), ("Meeting", "room tone + paper", "meeting"), ("Video call", "call connect", "call"), ("Presenting on stage", "applause soft", "applause"),
 ("Lecture / classroom", "chalk", "chalk"), ("Student learning", "page flip", "page"), ("Hand holds object (palm prop H9)", "soft pop", "pop"),
 ("Hand pinches tiny person (E14)", "cartoon pinch squeak (subtle)", "squeak"), ("Falling person", "falling whoosh", "fall whoosh"), ("Jump", "jump whoosh", "jump"),
])

CATS["MUSIC"] = ("Music structure & mix decisions", 0, "music edit points", [
 ("First frame", "music already playing (no fade-in from silence)", "-"), ("Hook ends (3s)", "music phrase / drum fill lands", "-"),
 ("Key claim line", "music drops out 0.5–1.5s (one per video)", "-"), ("After the drop", "beat returns with impact", "impact"),
 ("Voice speaking", "music ducked −10 to −14 dB via sidechain", "-"), ("No voice gap > 0.5s", "music rises back", "-"),
 ("Ending CTA", "music resolves on last bar, short tail", "-"), ("Clip with its own dialogue (ending clip)", "music −6 dB more, clip normalised", "-"),
 ("Talking-head premium (F1/F8)", "lo-fi / soft piano bed", "lofi"), ("Energetic promo (F6/F7)", "trap/808 ~100–120 BPM", "trap"),
 ("Faceless education (F4)", "minimal electronic ~120 BPM", "minimal electronic"), ("Emotional story", "piano + strings", "piano"),
 ("Podcast reel (F5)", "ambient pad, very low", "ambient"), ("Signature typography (F9)", "dark cinematic pulse", "cinematic pulse"),
 ("Cuts on beat", "allowed for montage only (portfolio grid); SFX still on visuals", "-"), ("SFX bus", "high-pass 150 Hz, low-pass 9 kHz, shared short reverb", "-"),
 ("Loudness", "final −14 LUFS, true peak ≤ −1.5 dB", "-"), ("Too many SFX in 1s", "keep max 2 overlapping; drop the lower-priority one", "-"),
 ("Bangla voice sibilance", "de-esser before mix", "-"), ("Room noise", "afftdn gentle; never change voice character", "-"),
])

CATS["GFX"] = ("Graphic primitives & motion design", -14, "on the animation frame", [
 ("Line draws on (SVG stroke)", "pen stroke / thin swish", "line draw"), ("Curved line / bezier draws (E03)", "long thin whoosh", "line whoosh"),
 ("Circle draws around object", "marker circle", "marker circle"), ("Check mark appears", "positive tick", "check"), ("Cross mark appears", "error tick", "cross"),
 ("Plus sign appears", "pop", "plus"), ("Minus sign appears", "low tick", "minus"), ("Equals / result", "chime", "result"), ("Arrow grows", "stretch swish", "arrow grow"),
 ("Dots pop in arc (E06 1-7)", "ascending pops", "dots pop"), ("Grid lines appear", "soft digital sweep", "grid"), ("Ruler / HUD ticks", "tiny ticks", "hud ticks"),
 ("Orbit ellipse draws", "airy circle whoosh", "orbit"), ("Concentric rings pulse", "sonar ping", "sonar"), ("Ring pulse behind object (POUNDED)", "soft impact + ring", "ring impact"),
 ("Glow flash on element", "shimmer", "glow"), ("Particles burst", "sparkle burst", "particles"), ("Dust/particle text assembly (E10)", "granular shimmer", "granular"),
 ("Confetti", "confetti pop", "confetti"), ("Sparks from word (E15)", "spark crackle", "sparks"), ("Brush stroke under word", "brush swish", "brush"),
 ("Torn paper collage piece", "paper tear", "tear"), ("Polaroid drops in", "paper flap", "polaroid"), ("Push-pin card flies in (E12)", "card whoosh + pin tap", "pin tap"),
 ("Card flips", "card flip", "card flip"), ("Card stack fans out", "card riffle", "riffle"), ("Glass HUD panel slides", "glass swish", "glass"),
 ("3D icon tile floats in", "soft whoosh", "float"), ("Object falls and lands", "fall whoosh + soft land", "fall land"), ("Object bounces", "boing soft", "boing"),
 ("Object swings on rope (E04)", "rope creak", "rope"), ("Object rotates", "rotation whoosh", "rotate"), ("Object scales up big", "swell", "swell"),
 ("Object shrinks away", "reverse swell", "shrink"), ("Object slides off screen", "swish out", "swish out"), ("Object replaces letter (E08)", "pop", "pop"),
 ("Duotone object pixel-assembles", "digital blip", "digital blip"), ("Spotlight turns on", "stage light clunk", "spotlight"), ("Curtain / reveal", "curtain swish", "curtain"),
 ("Shape morph", "liquid morph", "morph"), ("Liquid fill in text (E07)", "water swell", "water"), ("Gradient background shift", "none", "-"),
 ("Doodle squiggle wiggles", "none (too busy)", "-"), ("Speed lines stamp (E11 SECRET)", "zip stamp", "stamp zip"), ("Shock lines !!! (E15)", "cartoon alert", "alert"),
 ("AI orb pulses (E07)", "airy tonal hum", "orb"), ("Audio wave strip reacts", "none (visual of voice)", "-"), ("Countdown ring (E06)", "tick per second", "tick"),
 ("Progress underline fills (E11)", "rise sweep", "progress"), ("Map card floats (E16)", "soft pop", "pop"),
])

CATS["DATA"] = ("Charts & data", -13, "on the data event", [
 ("Bar grows", "rising tone per bar", "bar rise"), ("Bars grow in sequence", "ascending plucks", "plucks"), ("Line chart draws upward", "rising sweep", "rise"),
 ("Line chart crashes (E13)", "falling zig-zag tone", "fall"), ("Pie slices pop", "pop per slice", "pop"), ("Percentage counts", "tick train", "ticks"),
 ("Before vs after numbers", "low tone then bright ding", "before after"), ("Stat card appears", "card pop", "card"), ("Big statistic reveal", "hit + shimmer", "stat hit"),
 ("Source citation / article card (E09)", "paper slide + tick", "article"), ("Table rows fill", "soft ticks", "ticks"), ("Comparison VS", "versus hit", "versus"),
 ("Ranking #1 to #5 (E13)", "pop per number", "rank pop"), ("Survey result", "chime", "chime"), ("Google rating 4.9", "star ticks + ding", "stars"),
])

CATS["DENT"] = ("Dental & doctor-website niche (Benzadid)", -12, "on the visual frame", [
 ("Tooth icon appears", "tooth ting", "tooth ting"), ("Smile reveal", "sparkle", "sparkle"), ("Dental implant screw", "ratchet click soft", "ratchet"),
 ("Root canal file", "fine metallic", "metal fine"), ("Whitening before/after", "sparkle sweep", "sparkle sweep"), ("Dental X-ray (OPG)", "scanner sweep", "scanner"),
 ("Intraoral scanner", "electronic beep", "beep"), ("Autoclave", "steam hiss short", "steam"), ("RVG sensor", "click + beep", "beep"),
 ("Chamber signboard", "neon buzz / light on", "neon"), ("Doctor's website hero", "soft swell + click", "hero"), ("Doctor profile photo", "camera shutter soft", "shutter"),
 ("Degrees and credentials list", "paper + ticks", "credentials"), ("Patient testimonial card", "card pop + warm chime", "testimonial"), ("Book appointment button", "button click + success", "booking"),
 ("WhatsApp chat button", "message pop", "whatsapp"), ("Google Business profile", "pin + ding", "gbp"), ("Clinic location map", "pin drop", "pin"),
 ("Services carousel", "soft swipe per slide", "carousel"), ("Before website: outdated", "glitch + dusty", "old"), ("After website: modern", "shimmer + chime", "modern"),
 ("Bilingual toggle EN/BN", "switch click", "switch"), ("Admin panel login", "lock unlock", "unlock"), ("Blog post published", "publish whoosh", "publish"),
 ("Video library on site", "play click", "play"), ("Symptom checker", "digital tick", "tick"), ("Online payment", "payment success", "payment"),
 ("Mobile responsive demo (phone rotates)", "rotate whoosh", "rotate"), ("Speed score 100", "ticks + ding", "score"), ("Patients finding doctor on Google", "search typing + results", "search"),
 ("Competitor clinic", "neutral tick", "tick"), ("Doctor's specialty icon (eye/heart/bone)", "matching medical sound", "medical"),
 ("Portfolio card (Sikdar/ClientB/ClientD/Client-A)", "soft click per card", "click"), ("Benzadid logo", "brand sting soft", "logo sting"), ("Price/package card", "card pop", "card"),
])

CATS["SOCIAL"] = ("Social media & marketing", -13, "on the visual frame", [
 ("Reel play", "play click", "play"), ("Views counter", "tick train", "ticks"), ("Viral / explode", "whoosh + impact", "viral"), ("Algorithm", "digital chirp", "chirp"),
 ("Followers grow", "rising arpeggio", "grow"), ("Comment section", "multiple pops", "pops"), ("Share button", "whoosh", "share"), ("Save bookmark", "click", "save"),
 ("DM inbox", "message pings", "pings"), ("Story ring", "tap", "tap"), ("Live badge", "beep", "live"), ("Hashtag", "tick", "tick"), ("Ad campaign launch", "launch", "launch"),
 ("Boost post", "rise", "rise"), ("Engagement chart", "rise", "rise"), ("Unfollow / drop", "fall", "fall"), ("Trending", "fire whoosh", "fire"),
])

CATS["EDU"] = ("Education & explanation devices", -14, "on the visual frame", [
 ("Step 1 / 2 / 3 title", "whoosh + numbered pop", "step"), ("Tip / pro tip label", "ding small", "tip"), ("Mistake #N", "error tick + low thud", "mistake"),
 ("Myth vs fact", "buzzer then ding", "myth fact"), ("Correct answer", "ding", "correct"), ("Wrong answer", "buzzer soft", "wrong"),
 ("Definition card", "page chime", "definition"), ("Quote from expert", "paper + soft chime", "quote"), ("Example box", "card pop", "card"),
 ("Summary checklist", "tick per item", "checklist"), ("Warning sign", "alert tone soft", "warning"), ("Did you know?", "curious music box", "curious"),
 ("Formula E=mc2 (E14)", "8-bit blip + fire whoosh", "8bit fire"), ("Diagram labels pop", "tiny ticks", "ticks"), ("Zoom into diagram part", "soft wind", "wind"),
])

CATS["BD"] = ("Bangladesh / local context", -14, "on the visual frame", [
 ("Dhaka skyline", "city ambience light", "city"), ("Rickshaw", "rickshaw bell", "rickshaw bell"), ("Bus / traffic jam", "horns distant", "horns"),
 ("Chamber at night", "crickets + tube light hum", "night"), ("Rain monsoon", "rain", "rain"), ("Tea stall", "cup clink", "tea"), ("bKash payment", "payment success", "payment"),
 ("Taka coins", "coin", "coin"), ("Prayer time context", "avoid religious audio; use soft ambience", "-"), ("Village / rural patient", "birds + wind", "rural"),
 ("Hospital crowd BD", "murmur", "murmur"), ("Pharmacy", "pill rattle", "pills"), ("Mobile phone in hand", "tap", "tap"), ("Facebook page (BD clinics)", "notification", "notification"),
])
